version: "3"
services:
 
  database:
    container_name: database
    image: valravnx/econstitucional
    ports:
      - "6432:5432"

  pgAdmin:
    container_name: pgAdmin
    depends_on:
      - database
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
networks:
  default:
    driver: bridge